<a href="https://colab.research.google.com/github/RiazullJannat/ML/blob/main/ML_Assignment_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

## Exam Instructions:
1. প্রথমে নিচের cell এ নিজের **নাম** এবং কোর্সে registration করা **ইমেইল** দিবে
2. Question wise numbering করে Text cell রাখবে এবং এর নিচে Code cell থাকবে, চেষ্টা করবে একটি code cell এ একটি question উত্তর দেওয়ার
3. Google Colab এর মধ্যে কোডগুলো করবে
4. এবং সেই ফাইলটি **'Anyone with the link' & 'View' Access** দিয়ে ফাইলটির Shareable Link টি সাবমিট করবে

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [63]:
# Fill in your information
name = "Riazull Jannat"           # Write your full name here
email = "ramimk097@gmail.com"          # Write your registered email here

print(f"Name  : {name}")
print(f"Email : {email}")

Name  : Riazull Jannat
Email : ramimk097@gmail.com

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [64]:
# Question 1
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

df=pd.read_csv("./sample_data/house_price_regression_dataset.csv")
print(f"Dataset Shape:{df.shape}\n")
print("Dataset's first 10 rows:")
display(df.head(10))
print("\n\nDataset's 5 random samples:")
display(df.sample(5))

Dataset Shape:(1000, 8)

Dataset's first 10 rows:

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
5,3944,5,3,1990,2.475930,2,8,8.797970e+05
6,3671,1,2,2012,4.911960,0,1,8.144279e+05
7,3419,1,1,1972,2.805281,1,1,7.034131e+05
8,630,3,3,1997,1.014286,1,8,1.738750e+05
9,2185,4,2,1981,3.941604,2,5,5.041765e+05

Dataset's 5 random samples:

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
189,2302,5,2,1957,2.206074,2,3,5.019136e+05
357,2641,2,3,1998,4.564359,0,7,6.218628e+05
150,4597,3,2,2016,3.680770,0,9,1.006940e+06
118,4127,1,2,1990,4.216630,1,4,8.865683e+05
606,1829,4,3,1959,3.417062,0,4,4.179006e+05

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [65]:
#Question 2
cols_info = df.isnull().mean()

#droping columns with more than 50% missing values
cols_to_drop = cols_info[cols_info>0.5].index
df.drop(columns=cols_to_drop)

# Impute missing numerical and categorical values
num_cols = df.select_dtypes(include=[np.number]).columns.drop("House_Price")
cat_cols = df.select_dtypes(include=['object', 'category']).columns

if len(num_cols) > 0:
  df[num_cols] = SimpleImputer(strategy='mean').fit_transform(df[num_cols])
if len(cat_cols) > 0:
  df[cat_cols] = SimpleImputer(strategy='most_frequent').fit_transform(df[cat_cols])


# Performing Train test split
X = df.drop(["House_Price"], axis=1)
y = df['House_Price']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)


print(f"Shape of X_Train: {X_train.shape}\n")
print(f"Shape of X_Test: {X_test.shape}\n")
print(f"Shape of y_Train: {y_train.shape}\n")
print(f"Shape of y_Test: {y_test.shape}\n")

Shape of X_Train: (800, 7)

Shape of X_Test: (200, 7)

Shape of y_Train: (800,)

Shape of y_Test: (200,)

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

In [66]:
#Question 3

#decleareing prediction function
def make_prediction(x,w,b):
  m = x.shape[0]
  pred_list = np.zeros((m,))


  for i in range(m):
    pred_list[i] = w*x[i]+b
  return pred_list

# compute cost
def compute_cost(x, y, w, b):
    m = x.shape[0]
    cost_sum = 0.0

    for i in range(m):
        f_wb = w * x[i] + b
        cost_sum += (f_wb - y[i]) ** 2
    total_cost = cost_sum / (2 * m)

    return total_cost

# declearing calculate gradient function
def calculate_gradient(X,y,w,b):
  m = X.shape[0]
  dj_dw=0.0
  dj_db=0.0

  for i in range(m):
    prediction = w*X[i]+b
    error= prediction - y[i]
    dj_dw+=error*X[i]
    dj_db+=error
  return dj_dw/m,dj_db/m

# delearing calculate gradient decent function
def gradient_descent(X,y,w_inp,b_inp,max_itr,alpha):
  w=w_inp
  b=b_inp
  for i in range(max_itr):
    dj_dw,dj_db = calculate_gradient(X,y,w,b)
    w = w - alpha * dj_dw
    b = b - alpha * dj_db

  return w, b


# sceling value because X value become unhandalable when w*x[i]+b
X_test_q3=X_test['Square_Footage'].to_numpy()
X_train_q3 = X_train['Square_Footage'].to_numpy()
y_train_q3 = y_train.to_numpy()

X_mean, X_std = np.mean(X_train_q3), np.std(X_train_q3)

X_scaled = (X_train_q3 - X_mean) / X_std

# X_test_scaled = (X_test_q3 - X_mean) / X_std

alpha = 0.01
max_itr = 2000
w_init = 0.0
b_init = 0.0

w_scaled, b_scaled = gradient_descent(X_scaled, y_train_q3, w_init, b_init, max_itr, alpha)

#converting to original data format
w_final = w_scaled / X_std
b_final = b_scaled - (w_scaled * X_mean / X_std)

print("\n--- Learned Parameters ---")
print(f"Learned Slope (m): {w_final:.4f}")
print(f"Learned Intercept (c): {b_final:.4f}")
print("-" * 26)


y_test_pred = make_prediction(X_test_q3, w_final, b_final)

print("\n--- Test Set Predictions ---")
for sq_ft, price in zip(X_test_q3[:10], y_test_pred[:10]):
    print(f"Square Footage: {sq_ft} -> Predicted Price: ${price:,.2f}")

--- Learned Parameters ---
Learned Slope (m): 200.5569
Learned Intercept (c): 54229.0585
--------------------------

--- Test Set Predictions ---
Square Footage: 4012.0 -> Predicted Price: $858,863.25
Square Footage: 2310.0 -> Predicted Price: $517,515.44
Square Footage: 4708.0 -> Predicted Price: $998,450.83
Square Footage: 4932.0 -> Predicted Price: $1,043,375.57
Square Footage: 3646.0 -> Predicted Price: $785,459.43
Square Footage: 3586.0 -> Predicted Price: $773,426.02
Square Footage: 4638.0 -> Predicted Price: $984,411.85
Square Footage: 4127.0 -> Predicted Price: $881,927.29
Square Footage: 3781.0 -> Predicted Price: $812,534.61
Square Footage: 4243.0 -> Predicted Price: $905,191.89

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [67]:
#Question 4

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [68]:
# Question 5

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [69]:
# Question 6

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [70]:
# Question 7