<a href="https://colab.research.google.com/github/RiazullJannat/ML/blob/main/ML_M_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


from sklearn.linear_model import LogisticRegression

**1. Load the dataset**

In [4]:
# Load the dataset from a CSV file into a pandas DataFrame
df = pd.read_csv("./sample_data/titanic_dataset.csv")

# Display 5 random rows to see what the data looks like
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
536,537,no,first,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S
31,32,yes,first,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
173,174,no,third,"Sivola, Mr. Antti Wilhelm",male,21.0,0,0,STON/O 2. 3101280,7.9250,NaN,S
452,453,no,first,"Foreman, Mr. Benjamin Laventall",male,30.0,0,0,113051,27.7500,C111,C
516,517,yes,second,"Lemore, Mrs. (Amelia Milley)",female,34.0,0,0,C.A. 34260,10.5000,F33,S

In [5]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
204 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

**2. Feature Engineering**

In [6]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df['Cabin'] = df['Cabin'].fillna("Missing")

df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
752,753,no,third,"Vande Velde, Mr. Johannes Joseph",male,33.0,0,0,345780,9.500,Missing,S,1,M
187,188,yes,first,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,0,0,111428,26.550,Missing,S,1,M
467,468,no,first,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.550,Missing,S,1,M
53,54,yes,second,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.0,1,0,2926,26.000,Missing,S,2,M
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,Missing,S,1,M

In [7]:
df['Deck'].value_counts()

Deck
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [17]:
X = df.drop(["Survived","SibSp","Parch", "Cabin","Name","PassengerId"], axis=1)
y = df["Survived"]


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42, stratify=y)