In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [6]:
df = pd.read_csv("./sample_data/titanic_data_updated.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
#remove unnecessary columns
df.drop(["PassengerId","Name", "Ticket"], axis=1, inplace=True)
df

    Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         no   third    male  22.0      1      0   7.2500   NaN        S
1        yes   first  female  38.0      1      0  71.2833   C85        C
2        yes   third  female  26.0      0      0   7.9250   NaN        S
3        yes   first  female  35.0      1      0  53.1000  C123        S
4         no   third    male  35.0      0      0   8.0500   NaN        S
..       ...     ...     ...   ...    ...    ...      ...   ...      ...
886       no  second    male  27.0      0      0  13.0000   NaN        S
887      yes   first  female  19.0      0      0  30.0000   B42        S
888       no   third  female   NaN      1      2  23.4500   NaN        S
889      yes   first    male  26.0      0      0  30.0000  C148        C
890       no   third    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [8]:
# spliting features and target columns

features = df.drop("Survived", axis=1)
target = df["Survived"]

In [9]:
features_train, features_test, target_train, target_test = train_test_split(features,target, test_size=0.2, random_state=42)
features_test.isnull().sum()

Pclass        0
Sex           0
Age          37
SibSp         0
Parch         0
Fare          0
Cabin       134
Embarked      0
dtype: int64

In [10]:
#declearing imputer
age_imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
embarked_imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
cabin_imputer = SimpleImputer(missing_values=np.nan, strategy="constant", fill_value="Missing", add_indicator=True)

#Learning the columns
age_imputer.fit(features_train[['Age']])
embarked_imputer.fit(features_train[["Embarked"]])
cabin_imputer.fit(features_train[['Cabin']])


#transforming the values
features_train['Age'] = age_imputer.transform(features_train[['Age']]).ravel()
features_train['Embarked']=embarked_imputer.transform(features_train[['Embarked']]).ravel()
features_train[["Cabin","cabin_indicator"]]=cabin_imputer.transform(features_train[['Cabin']])


features_test['Age'] = age_imputer.transform(features_test[['Age']]).ravel()
features_test['Embarked']=embarked_imputer.transform(features_test[['Embarked']]).ravel()
features_test[["Cabin","cabin_indicator"]]=cabin_imputer.transform(features_test[['Cabin']])


print("Train data set after clning nulls:\n")
display(features_train)

print("Test data set after clning nulls:\n")
display(features_test)

Train data set after clning nulls:

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_indicator
331,first,male,45.500000,0,0,28.5000,C124,S,False
733,second,male,23.000000,0,0,13.0000,Missing,S,True
382,third,male,32.000000,0,0,7.9250,Missing,S,True
704,third,male,26.000000,1,0,7.8542,Missing,S,True
813,third,female,6.000000,4,2,31.2750,Missing,S,True
...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,True
270,first,male,29.498846,0,0,31.0000,Missing,S,True
860,third,male,41.000000,2,0,14.1083,Missing,S,True
435,first,female,14.000000,1,2,120.0000,B96 B98,S,False
102,first,male,21.000000,0,1,77.2875,D26,S,False

Test data set after clning nulls:

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_indicator
709,third,male,29.498846,1,1,15.2458,Missing,C,True
439,second,male,31.000000,0,0,10.5000,Missing,S,True
840,third,male,20.000000,0,0,7.9250,Missing,S,True
720,second,female,6.000000,0,1,33.0000,Missing,S,True
39,third,female,14.000000,1,0,11.2417,Missing,C,True
...,...,...,...,...,...,...,...,...,...
433,third,male,17.000000,0,0,7.1250,Missing,S,True
773,third,male,29.498846,0,0,7.2250,Missing,C,True
25,third,female,38.000000,1,5,31.3875,Missing,S,True
84,second,female,17.000000,0,0,10.5000,Missing,S,True
10,third,female,4.000000,1,1,16.7000,G6,S,False

**Outlier detection**

In [11]:
mean_of_age = features_train['Age'].mean()
sd_of_age = features_train['Age'].std()

features_train['zscore_age']=(features_train['Age']-mean_of_age)/sd_of_age
features_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_indicator,zscore_age
331,first,male,45.500000,0,0,28.5000,C124,S,False,1.231398e+00
733,second,male,23.000000,0,0,13.0000,Missing,S,True,-5.001304e-01
382,third,male,32.000000,0,0,7.9250,Missing,S,True,1.924808e-01
704,third,male,26.000000,1,0,7.8542,Missing,S,True,-2.692600e-01
813,third,female,6.000000,4,2,31.2750,Missing,S,True,-1.808396e+00
...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,True,-6.540440e-01
270,first,male,29.498846,0,0,31.0000,Missing,S,True,2.734055e-16
860,third,male,41.000000,2,0,14.1083,Missing,S,True,8.850920e-01
435,first,female,14.000000,1,2,120.0000,B96 B98,S,False,-1.192742e+00
102,first,male,21.000000,0,1,77.2875,D26,S,False,-6.540440e-01

In [12]:
age_outliers = features_train[abs(features_train['zscore_age'])>3]
age_outliers

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_indicator,zscore_age
116,third,male,70.5,0,0,7.750,Missing,Q,True,3.155317
745,first,male,70.0,1,1,71.000,B22,S,False,3.116839
630,first,male,80.0,0,0,30.000,A23,S,False,3.886407
851,third,male,74.0,0,0,7.775,Missing,S,True,3.424666
672,second,male,70.0,0,0,10.500,Missing,S,True,3.116839

In [13]:
mean_of_fare = features_train['Fare'].mean()
std_of_fare = features_train['Fare'].std()

features_train['zscore_fare'] = (features_train['Fare']-mean_of_fare)/std_of_fare
features_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_indicator,zscore_age,zscore_fare
331,first,male,45.500000,0,0,28.5000,C124,S,False,1.231398e+00,-0.078628
733,second,male,23.000000,0,0,13.0000,Missing,S,True,-5.001304e-01,-0.376880
382,third,male,32.000000,0,0,7.9250,Missing,S,True,1.924808e-01,-0.474533
704,third,male,26.000000,1,0,7.8542,Missing,S,True,-2.692600e-01,-0.475896
813,third,female,6.000000,4,2,31.2750,Missing,S,True,-1.808396e+00,-0.025232
...,...,...,...,...,...,...,...,...,...,...,...
106,third,female,21.000000,0,0,7.6500,Missing,S,True,-6.540440e-01,-0.479825
270,first,male,29.498846,0,0,31.0000,Missing,S,True,2.734055e-16,-0.030523
860,third,male,41.000000,2,0,14.1083,Missing,S,True,8.850920e-01,-0.355554
435,first,female,14.000000,1,2,120.0000,B96 B98,S,False,-1.192742e+00,1.682019
102,first,male,21.000000,0,1,77.2875,D26,S,False,-6.540440e-01,0.860143

In [14]:
outliers_of_fare = features_train[abs(features_train['zscore_fare'])>3]
print(len(outliers_of_fare))
outliers_of_fare

17

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_indicator,zscore_age,zscore_fare
118,first,male,24.000000,0,1,247.5208,B58 B60,C,False,-4.231736e-01,4.135780
716,first,female,38.000000,0,0,227.5250,C45,C,False,6.542216e-01,3.751020
377,first,male,27.000000,0,2,211.5000,C82,C,False,-1.923032e-01,3.442666
742,first,female,21.000000,2,2,262.3750,B57 B59 B63 B66,C,False,-6.540440e-01,4.421605
380,first,female,42.000000,0,0,227.5250,Missing,C,True,9.620488e-01,3.751020
779,first,female,43.000000,0,1,211.3375,B3,S,False,1.039006e+00,3.439539
730,first,female,29.000000,0,0,211.3375,B5,S,False,-3.838960e-02,3.439539
88,first,female,23.000000,3,2,263.0000,C23 C25 C27,S,False,-5.001304e-01,4.433631
341,first,female,24.000000,3,2,263.0000,C23 C25 C27,S,False,-4.231736e-01,4.433631
557,first,male,29.498846,0,0,227.5250,Missing,C,True,2.734055e-16,3.751020
737,first,male,35.000000,0,0,512.3292,B101,C,False,4.233512e-01,9.231235
679,first,male,36.000000,0,1,512.3292,B51 B53 B55,C,False,5.003080e-01,9.231235
438,first,male,64.000000,1,4,263.0000,C23 C25 C27,S,False,2.655098e+00,4.433631
689,first,female,15.000000,0,1,211.3375,B5,S,False,-1.115785e+00,3.439539
258,first,female,35.000000,0,0,512.3292,Missing,C,True,4.233512e-01,9.231235
27,first,male,19.000000,3,2,263.0000,C23 C25 C27,S,False,-8.079576e-01,4.433631
700,first,female,18.000000,1,0,227.5250,C62 C64,C,False,-8.849144e-01,3.751020

##Outliers Using IQR

In [19]:
age_q1 = features_train['Age'].quantile(0.25)
age_q3 = features_train['Age'].quantile(0.75)

# print(age_q1, age_q3)
age_iqr = age_q3 - age_q1

min_age = age_q1-1.5*age_iqr
max_age = age_q3+1.5*age_iqr

# print(min_age, max_age)

age_outlier = features_train[(features_train['Age']<min_age) | (features_train['Age']>max_age)]

display(age_outlier)

,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked,cabin_indicator,zscore_age,zscore_fare
326,third,male,61.00,0,0,6.2375,Missing,S,True,2.424228,-0.507004
483,third,female,63.00,0,0,9.5875,Missing,S,True,2.578141,-0.442543
7,third,male,2.00,3,1,21.0750,Missing,S,True,-2.116223,-0.221500
305,first,male,0.92,1,2,151.5500,C22 C26,S,False,-2.199336,2.289105
829,first,female,62.00,0,0,80.0000,B28,S,False,2.501185,0.912337
626,second,male,57.00,0,0,12.3500,Missing,Q,True,2.116401,-0.389387
456,first,male,65.00,0,0,26.5500,E38,S,False,2.732055,-0.116150
172,third,female,1.00,1,1,11.1333,Missing,S,True,-2.193180,-0.412799
164,third,male,1.00,4,1,39.6875,Missing,S,True,-2.193180,0.136642
381,third,female,1.00,0,2,15.7417,Missing,C,True,-2.193180,-0.324124
694,first,male,60.00,0,0,26.5500,Missing,S,True,2.347271,-0.116150
587,first,male,60.00,1,1,79.2000,B41,C,False,2.347271,0.896943
570,second,male,62.00,0,0,10.5000,Missing,S,True,2.501185,-0.424985
879,first,female,56.00,0,1,83.1583,C50,C,False,2.039444,0.973109
94,third,male,59.00,0,0,7.2500,Missing,S,True,2.270314,-0.487522
11,first,female,58.00,0,0,26.5500,C103,S,False,2.193357,-0.116150
644,third,female,0.75,2,1,19.2583,Missing,C,True,-2.212419,-0.256458
15,second,female,55.00,0,0,16.0000,Missing,S,True,1.962487,-0.319154
530,second,female,2.00,1,1,26.0000,Missing,S,True,-2.116223,-0.126733
340,second,male,2.00,1,1,26.0000,F2,S,False,-2.116223,-0.126733
487,first,male,58.00,0,0,29.7000,B37,C,False,2.193357,-0.055538
467,first,male,56.00,0,0,26.5500,Missing,S,True,2.039444,-0.116150
827,second,male,1.00,0,2,37.0042,Missing,C,True,-2.193180,0.085010
116,third,male,70.50,0,0,7.7500,Missing,Q,True,3.155317,-0.477901
745,first,male,70.00,1,1,71.0000,B22,S,False,3.116839,0.739159
268,first,female,58.00,0,1,153.4625,C125,S,False,2.193357,2.325906
479,third,female,2.00,0,1,12.2875,Missing,S,True,-2.116223,-0.390590
195,first,female,58.00,0,0,146.5208,B80,C,False,2.193357,2.192333
16,third,male,2.00,4,1,29.1250,Missing,Q,True,-2.116223,-0.066602
469,third,female,0.75,2,1,19.2583,Missing,C,True,-2.212419,-0.256458
630,first,male,80.00,0,0,30.0000,A23,S,False,3.886407,-0.049765
152,third,male,55.50,0,0,8.0500,Missing,S,True,2.000966,-0.472128
684,second,male,60.00,1,1,39.0000,Missing,S,True,2.347271,0.123413
119,third,female,2.00,4,2,31.2750,Missing,S,True,-2.116223,-0.025232
297,first,female,2.00,1,2,151.5500,C22 C26,S,False,-2.116223,2.289105
851,third,male,74.00,0,0,7.7750,Missing,S,True,3.424666,-0.477420
183,second,male,1.00,2,1,39.0000,F4,S,False,-2.193180,0.123413
438,first,male,64.00,1,4,263.0000,C23 C25 C27,S,False,2.655098,4.433631
788,third,male,1.00,1,2,20.5750,Missing,S,True,-2.193180,-0.231122
672,second,male,70.00,0,0,10.5000,Missing,S,True,3.116839,-0.424985
386,third,male,1.00,5,2,46.9000,Missing,S,True,-2.193180,0.275425
232,second,male,59.00,0,0,13.5000,Missing,S,True,2.270314,-0.367259
824,third,male,2.00,4,1,39.6875,Missing,S,True,-2.116223,0.136642
803,third,male,0.42,0,1,8.5167,Missing,C,True,-2.237815,-0.463148
170,first,male,61.00,0,0,33.5000,B19,S,False,2.424228,0.017582
755,second,male,0.67,1,1,14.5000,Missing,S,True,-2.218576,-0.348017
642,third,female,2.00,3,2,27.9000,Missing,S,True,-2.116223,-0.090174
647,first,male,56.00,0,0,35.5000,A26,C,False,2.039444,0.056066
492,first,male,55.00,0,0,30.5000,C30,S,False,1.962487,-0.040144
555,first,male,62.00,0,0,26.5500,Missing,S,True,2.501185,-0.116150
205,third,female,2.00,0,1,10.4625,G6,S,False,-2.116223,-0.425707
366,first,female,60.00,1,0,75.2500,D37,C,False,2.347271,0.820937
831,second,male,0.83,1,1,18.7500,Missing,S,True,-2.206263,-0.266238
252,first,male,62.00,0,0,26.5500,C87,S,False,2.501185,-0.116150